[[redirects]]
  from = "/crm/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Role = ["estimator", "admin"] }

[[redirects]]
  from = "/crm/*"
  to = "/login"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["netlify/functions/assets/*"]